### ISSUE TITLE
Support 256

### ISSUE THREAD

**Issue by felippenardi** [raphamorim/lucario#22]
Just tried it on my terminal and this was the result:
![screenshot 2014-08-01 15 54 31](https://cloud.githubusercontent.com/assets/1354492/3783518/8f5ea0ec-19ad-11e4-807c-9ae5b83c7f26.png)

I guess this is something related to supporting color 256.

**Comment by panosl** [comment]
Fixed those two in my branch, see if it resolves it for you guys: https://github.com/panosl/lucario
