### ISSUE TITLE
Target the selector `:host, atom-text-editor` instead of `.editor` for shadow DOM support.

### ISSUE THREAD

**Issue by J3Rik0** [raphamorim/lucario#28]
In index.less: Target the selector `:host, atom-text-editor` instead of `.editor` for shadow DOM support.

**Comment by t4r0** [comment]
@raphamorim I Rewrote the source code from your repo, to fit the new atom 1.0 conventions. Not sure if you're accepting pull requests. Since i really like your palette and just as @J3Rik0 says atom is no longer supporting some selectors.

**Comment by raphamorim** [comment]
Oh, I forgot to resolve. @t4r0 you can send the PR to solve this problem?

**Comment by t4r0** [comment]
Of course PR #32 is ready, now.
