### ISSUE TITLE
vim-airline

### ISSUE THREAD

**Issue by caiocutrim** [raphamorim/lucario#30]
Hello dude, what is up? I am here to ask you about your project, I think that it is a good color scheme and I think that could be included as vim-airline color scheme in a future... :dancers: :+1:

**Comment by raphamorim** [comment]
Yeah, I agree. This is a great idea. But I don't know if lucario vim theme is stable enough to be incluided in vim airline themes.

Lucario for vim still have a open issue. :/

https://github.com/raphamorim/lucario/issues/22

**Comment by raphamorim** [comment]
Hi @caiocutrim,

I think this issue is already solve by https://github.com/raphamorim/lucario/pull/39

Let me know if this problem persists

**Comment by rlue** [comment]
Sorry to resurrect a closed issue. It's now 2020 and Lucario is still an awesome color scheme but is not officially bundled into the official [vim-airline-themes](https://github.com/vim-airline/vim-airline-themes/tree/master/autoload/airline/themes) repo. However, it would be possible to create an unofficial lucario theme for vim-airline, and bundle it in _this_ repo.

For example, [iceberg does this exact thing](https://github.com/cocopon/iceberg.vim/tree/master/autoload/airline/themes).

Would the owner be open to a PR for this?
