### ISSUE TITLE
Atom: Something causes the gutter line numbers to disappear/reappear at random occasions

### ISSUE THREAD

**Issue by dsifford** [raphamorim/lucario#34]
Hi there,

Came across another issue that I unfortunately don't have the time to troubleshoot (for now).

Something with your atom theme causes the gutter to go crazy and hide line numbers at random intervals. It really is quite unpredictable.

Here's a screenshot:

![image](https://cloud.githubusercontent.com/assets/5240018/12632907/b655a136-c529-11e5-911a-2cd435a12fd4.png)

Let me know what you think. I'll see if I can get to troubleshooting this further in a week or so when I have more time.

Thanks

Edit: I have a sneaking suspicion that it has something to do with the `git diff` package. It only happens on lines that are marked as edited, removed, or added..

**Comment by raphamorim** [comment]
Sorry, by the delay :/
It wasn't to happen. Can you help me to solve this?

**Comment by dsifford** [comment]
@raphamorim Yep, sure can. 

Another thing I noticed is, it seems to only occur where there are line deletions marked by git-diff. (eg. the red-looking line just above line 55 in the example photo)

**Comment by raphamorim** [comment]
I see, this is bad. 
I stopped using the Atom a while back. So it has been difficult to find problems.

**Comment by dsifford** [comment]
Update: It's definitely an issue with the `git diff` package (specifically, line removals) 

[Screencapture](http://www.screencast.com/t/qh1AAB3dw)

Will troubleshoot this later this evening if I can find the time.
