### ISSUE TITLE
self, this, etc keywords

### ISSUE THREAD

**Issue by cesarvh** [raphamorim/lucario#36]
I guess this is more of a suggestion than an issue. This is hands down the best theme I have ever had for sublime. Except one thing: the instance keywords `this` and `self` for java and python respectively are unaffected and though i tried changing them myself, i couldn't. Would someone mind pointing me in the right direction as to how i should change these, or can i just suggest it become implemented? It would be 100x better :+1:

**Comment by raphamorim** [comment]
cc// @barbier

**Comment by raphamorim** [comment]
Closing per inactivity.
