### ISSUE TITLE
Tabs show up as white using One Dark UI theme in Atom

### ISSUE THREAD

**Issue by qolop** [raphamorim/lucario#37]
The One Dark theme happens to currently be the default UI theme in Atom. Tabs in the One Dark theme (and other UI themes) show up as white when using Lucario, which is clearly not intended.

![](https://i.imgur.com/lEBtplj.png)

**Comment by raphamorim** [comment]
@barbier can you see it?

**Comment by raphamorim** [comment]
Hi @qolop sorry by delay.

Fixed now! :octocat: 
Just change to [Lucario 2.0.0](https://atom.io/themes/lucario)
