### ISSUE TITLE
tmux + vim + iterm2: i'm not sure how to make the correct color

### ISSUE THREAD

**Issue by spencer1573** [raphamorim/lucario#38]
here is what happens when i put the color theme into iterm2.
![screen shot 2016-05-18 at 8 10 04 am](https://cloud.githubusercontent.com/assets/4762850/15361794/3561f396-1cd0-11e6-8569-65b92a27d80a.png)

and here is what happens when i allow the lucario theme in vim, while running the same color schemes in iterm2
![screen shot 2016-05-18 at 8 10 43 am](https://cloud.githubusercontent.com/assets/4762850/15361819/54891f06-1cd0-11e6-9063-c5ee112311d4.png)

this is what it looks like when i don't change iterms color themes at all:
![screen shot 2016-05-18 at 8 14 32 am](https://cloud.githubusercontent.com/assets/4762850/15361889/a02d380c-1cd0-11e6-9e9d-80c9d1819c47.png)

this is macs stock terminal program:
![screen shot 2016-05-18 at 8 17 41 am](https://cloud.githubusercontent.com/assets/4762850/15362096/418683ca-1cd1-11e6-82da-b81b93a26bd3.png)

and i checked that for both iterm2 and iterm
the echo $TERM is:
screen-256color or 

and it doesn't work when i get out of tmux

I'm confused about how to get this awesome color sheme to work!

Thanks so much in advance!

**Comment by panosl** [comment]
I am having the same issue. Works fine in Yosemite Terminal app though.

![screenshot 2016-05-23 12 10 10](https://cloud.githubusercontent.com/assets/91211/15465994/13c4f404-20e0-11e6-8468-b208b7467f8b.png)

Any ideas?

**Comment by panosl** [comment]
Found a fix,

open your lucario.vim theme and on line 39 change ctermbg=0 to NONE like so:

hi Normal ctermfg=231 ctermbg=NONE cterm=NONE guifg=#f8f8f2 guibg=#2b3e50 gui=NONE

**Comment by panosl** [comment]
@spencer1573 fixed it on my branch, give it a go: https://github.com/panosl/lucario

**Comment by raphamorim** [comment]
@panosl can you send a PR with this changes?

**Comment by panosl** [comment]
@raphamorim just did, pull it away Raphael!

**Comment by raphamorim** [comment]
Awesome @panosl ! Already Merged :))
