### ISSUE TITLE
Support Visual Studio Code

### ISSUE THREAD

**Issue by gabrielmoreira** [raphamorim/lucario#43]
The fast way - Convert Lucario.tmTheme to vscode theme:
https://code.visualstudio.com/Docs/customization/themes#_adding-a-new-theme

**Comment by paulmolluzzo** [comment]
Until one is officially published you can do this:

```bash
$ npm install -g yo generator-code
$ yo code
```

Then in the prompts choose:
1. "New Color Theme"
2. "Import an existing theme and inline it in the Visual Studio Code color theme file."
3. Paste this URL `https://raw.githubusercontent.com/raphamorim/lucario/master/Lucario.tmTheme` as the URL of the textmate 
4. Name it (I used the default)
5. Make an identifier (I used the default)
6. Add description
7. Add your publisher name (I wrote `none`)
8. Name of theme (I used the default)
9. Select base theme: `Dark`

Then I copied the created directory to `~/.vscode/extensions/` and changed the name of my theme in the settings to Lucario.

Done!

**Comment by Ikuyadeu** [comment]
Published https://marketplace.visualstudio.com/items?itemName=Ikuyadeu.lucario
Because this is MIT, and VS Code need some option color schema.

**Comment by paulmolluzzo** [comment]
👏👏👏

**Comment by raphamorim** [comment]
whoa that's NICE @Ikuyadeu! I love it! <3
Can you add a reference for it in lucario README?

**Comment by Ikuyadeu** [comment]
Sure.

**Comment by Ikuyadeu** [comment]
I created PR in #54
