### ISSUE TITLE
Support Gnome-Terminal

### ISSUE THREAD

**Issue by ghost** [raphamorim/lucario#49]
Absolutely love this theme! If possible, could you please support gnome-terminal? Should be easy I hope.

**Comment by JGH1000** [comment]
FYI I don't know how to create scripts for that but I entered everything manually in gnome-terminal - looks stunning. Next I will modify platformio-ide-terminal to match it. Please keep up the great work, can't believe there is a theme that looks better than one-dark.

**Comment by raphamorim** [comment]
Thanks @JGH1000 
I'm really happy after read your opinions about lucario.
Ok, let me know if you advance :)

**Comment by folixg** [comment]
[terminal.sexy](https://terminal.sexy) provides automatic creation of scripts for gnome-terminal color schemes. I will provide a PR.
