### ISSUE TITLE
Distribute with Vim?

### ISSUE THREAD

**Issue by chrisbra** [raphamorim/lucario#51]
there is an [issue](https://github.com/vim/vim/issues/1665) open in the vim repository, to distribute more colorschemes with Vim. Would you kindly give your permission to distribute this colorscheme with Vim?

**Comment by raphamorim** [comment]
Sure @chrisbra. It would be amazing :)

**Comment by chrisbra** [comment]
Well, I can collect your file and send it to Bram, or you can do it. I would prefer if you can do it, since you know obviously best, when it is kind of stable enough and of course you will know when to send updated theme to Bram for inclusion. If you would like to do it mention that this is for fixing issue 1665. thanks!

**Comment by raphamorim** [comment]
@chrisbra sorry for my ignorance.
To do it, I'll send a mail for vim-dev@vim.org with `lucario.vim` attached to email and referencing vim/vim#1665 ?

**Comment by chrisbra** [comment]
that would be great.

**Comment by raphamorim** [comment]
email sent @chrisbra :octocat: 

This print screen is more to me than one, just for help me to record later :D

![screen shot 2017-08-03 at 08 42 41](https://user-images.githubusercontent.com/3630346/28920393-084dc1fa-7828-11e7-82ee-fdeb82013fff.png)
