### ISSUE TITLE
Colour highlighting of Julia functions - difference in Atom and Sublime

### ISSUE THREAD

**Issue by luboshanus** [raphamorim/lucario#56]
Hi,
I am wondering whether you do not know why the scheme highlight the same code differently in Atom and Sublime. The desired one is the one of Atom.

Atom example [correct]:
![screenshot 2018-10-10 at 12 11 51](https://user-images.githubusercontent.com/2473206/46729458-b4c00580-cc85-11e8-8d16-73fadd2afc6d.png)

Sublime example (functions are of the colour of text):
![screenshot 2018-10-10 at 12 04 05](https://user-images.githubusercontent.com/2473206/46729392-82160d00-cc85-11e8-9aab-c4f530425419.png)

Thank you for ideas.

**Comment by raphamorim** [comment]
Probably we lost that style migrating lucario to Atom 2.0. Do you mind to fix that? Probably will be just some changes on https://github.com/raphamorim/lucario/tree/master/styles

**Comment by raphamorim** [comment]
Closing per inactivity.
