### ISSUE TITLE
[VIM] The visual mode selection is black in terminal vim.

### ISSUE THREAD

**Issue by israelst** [raphamorim/lucario#67]
Hi, @raphamorim. I'm using Lucario as my color scheme on Vim within the terminal. Given that the background is dark, I'm wondering if `16` is an aproprieted color for the visual mode selection. Is this the intended behavior?

![Screenshot from 2020-10-03 21-11-33](https://user-images.githubusercontent.com/92998/95004103-112c3600-05bd-11eb-90b9-d39dd8a1728f.png)

I would expect something like:

![Screenshot from 2020-10-03 21-33-32](https://user-images.githubusercontent.com/92998/95004333-2e163880-05c0-11eb-8a45-c4b680aca82b.png)

Which means replace `16` by `60` on the following line:

```vim
hi Visual       ctermfg=NONE ctermbg=16 cterm=NONE guifg=NONE guibg=#19242f gui=NONE
```

If it is ok for you, I'll be happy to send a PR.

**Comment by israelst** [comment]
There actually is a way of using the GUI colors while using terminals that supports more than 256 colors:

```vim
set termguicolors
```

Still, the suggested change from `16` to `60` would keep the palette and provide a better experience in cases without good color support.

**Comment by raphamorim** [comment]
Believe was fixed lately, please feel free to reopen this issue
